version: '3.8'

services:
  database:
    image: postgres:15
    container_name: recruitring-db
    environment:
      POSTGRES_DB: recruitring-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: recruitring-backend
    depends_on:
      - database
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/recruitring-db
    ports:
      - "8443:8443"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: recruitring-frontend
    ports:
      - "4200:4200"

volumes:
  db_data:
